docs: ✏️ minor edits for clarity and readability
rostools/r-cubed-advanced pull request #218
Opened 2024-12-04 16:20 UTC by signekb

## Description

This PR:
- adds some text edits for clarity and readability. 
- adds a panel-tabset for the file and folder structure at the beginning and end of the course
- adds a `sticky-up` note block in `includes/` that can be reused in other exercises. 

This PR needs an in-depth review.

## Checklist

- [X] Ran spell-check
- [X] Formatted Markdown
- [X] Rendered website locally

2024-12-04 19:31 UTC, signekb commented on includes/_sticky_up.qmd
> +When you're reading to continue, place the sticky/paper hat on your
```suggestion
When you're ready to continue, place the sticky/paper hat on your
```

2024-12-04 19:42 UTC, signekb commented on sessions/introduction.qmd
> +-   Track package dependencies in the `DESCRIPTION` file.
Not sure this is the correct "replacement" of the outdated line mentioning a "project-specific environment"

2024-12-04 19:43 UTC, signekb commented on sessions/introduction.qmd
> +This structure also supports our workflow and processes throughout the
There's something about this overview of the workflow that isn't entirely clear to me. I'll think more about this as I go through the rest of the course material -- I want to make the diagram showing the workflow 👍

2024-12-04 20:41 UTC, lwjohnst86 requested changes
Nice! Only small suggestions/edits.

2024-12-04 20:41 UTC, lwjohnst86 commented on sessions/introduction.qmd
> +Where will we start end where will be end, in a more “tangible” way? The
```suggestion
Where will we start and where will be end, in a more "tangible" way? The
```

2024-12-04 20:41 UTC, lwjohnst86 commented on sessions/introduction.qmd
> +        markdown files.
```suggestion
        Markdown files.
```

2024-12-04 20:41 UTC, lwjohnst86 commented on sessions/introduction.qmd
> +    -   We restart R because it to ensure that the R workspace is
```suggestion
    -   We restart R because to ensure that the R workspace is
```

2024-12-04 20:41 UTC, lwjohnst86 commented on sessions/introduction.qmd
> +    -   We use Git to keep track of what changes was made to the files,
```suggestion
    -   We use Git to keep track of what changes were made to the files,
```

2024-12-05 12:57 UTC, lwjohnst86 commented on sessions/introduction.qmd
>  ## Reading task: \~10 minutes
Ooo that's cute!!

2024-12-05 12:58 UTC, lwjohnst86 approved these changes

2024-12-05 12:58 UTC, merged